"""Add TopicTTSAudio table

Revision ID: de1a09a1de4f
Revises: 25eaedd74d83
Create Date: 2026-02-21 22:37:37.221275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de1a09a1de4f'
down_revision: Union[str, Sequence[str], None] = '25eaedd74d83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic_tts_audio',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('audio_base64', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topic_tts_audio_language_code'), 'topic_tts_audio', ['language_code'], unique=False)
    op.create_index(op.f('ix_topic_tts_audio_topic_id'), 'topic_tts_audio', ['topic_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topic_tts_audio_topic_id'), table_name='topic_tts_audio')
    op.drop_index(op.f('ix_topic_tts_audio_language_code'), table_name='topic_tts_audio')
    op.drop_table('topic_tts_audio')
    # ### end Alembic commands ###
