"""Add Translation Tables

Revision ID: e552e6fd2995
Revises: c109c37a6911
Create Date: 2026-02-21 17:27:44.758640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e552e6fd2995'
down_revision: Union[str, Sequence[str], None] = 'c109c37a6911'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ui_translations',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('key', 'language_code')
    )
    op.create_table('topic_translations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topic_translations_language_code'), 'topic_translations', ['language_code'], unique=False)
    op.create_index(op.f('ix_topic_translations_topic_id'), 'topic_translations', ['topic_id'], unique=False)
    op.create_table('topic_content_translations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('translated_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['topic_contents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topic_content_translations_content_id'), 'topic_content_translations', ['content_id'], unique=False)
    op.create_index(op.f('ix_topic_content_translations_language_code'), 'topic_content_translations', ['language_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topic_content_translations_language_code'), table_name='topic_content_translations')
    op.drop_index(op.f('ix_topic_content_translations_content_id'), table_name='topic_content_translations')
    op.drop_table('topic_content_translations')
    op.drop_index(op.f('ix_topic_translations_topic_id'), table_name='topic_translations')
    op.drop_index(op.f('ix_topic_translations_language_code'), table_name='topic_translations')
    op.drop_table('topic_translations')
    op.drop_table('ui_translations')
    # ### end Alembic commands ###
